### ISSUE TITLE
help

### ISSUE THREAD

**Issue by alleneee** [HadXu/DC-5th#1]
最近在零基础学着尝试做这个题目,看了你的代码之后,有一些思路但是还是很晕,不知道能否麻烦你解解惑,QQ690904834

**Comment by HadXu** [comment]
哈哈 这个比赛代码有点乱。

**Comment by alleneee** [comment]
我看的头都大了,能不能整理一波啊  兄弟

**Comment by HadXu** [comment]
目前没有时间啊

**Comment by alleneee** [comment]
好吧 ipynb都是你们测试和预处理的文件吧,  py是出结果的文件吗?

**Comment by alleneee** [comment]
****好吧ipynb都是你们测试和预处理的文件吧，py是出结果的文件吗？

**Comment by HadXu** [comment]
是。
